### ISSUE TITLE
autoUpdateVariables should be key-value pairs instead of a list

### ISSUE THREAD

**Issue by bbayu123** [bergerhealer/SignLink#10]
Some times PAPI variables are just way too long to fit on signs. Thus key-value pairs should be defined instead of a plain list so that an alias can be defined for PAPI variables too long to fit on signs.

If there is an alternative, do let us know :3

**Comment by bergerkiller** [comment]
There is now, as of today, an alternative. You can alias variables by placing them as %variablename% text value of another variable. So, if you have a very long placeholder name:

%very_long_name%

You can now do:
```
/var edit short
/var set %very_long_name%
```

And it will show the value of very_long_name where you use %short% on signs. This also works when very_long_name has player-specific placeholder values.
