### ISSUE TITLE
Update PlaceholderAPI dependency and move away from deprecated methods

### ISSUE THREAD

**Issue by Andre601** [bergerhealer/SignLink#12]
PlaceholderAPI received a significant amount of changes recently.
Namely the following...

- Deprecation of `PlaceholderAPI.registerPlaceholderHook(Plugin|String, PlaceholderHook)`
- Deprecation of `PlaceholderAPI.getPlaceholders()`
- Deprecation of `PlaceholderAPI.unregisterPlaceholderHook(Plugin|String)`
- Deprecation of `PlaceholderHook` entirely.

Things should now be handled mainly through the PlaceholderExpansion method, namely the registering/unregistering of a class as PlaceholderExpansion.

The methods above are scheduled to be removed in 2.11.0 which may or may not take some time.

It is also important to note that the aforementioned methods won't do anything anymore. They will now only print a warning and return null.

**Comment by bergerkiller** [comment]
This should now be implemented
