### ISSUE TITLE
SignLink causes significant tps lag because of unknown reasons (a lot of tile entities reported)

### ISSUE THREAD

**Issue by bergerkiller** [bergerhealer/SignLink#3]
There are reports of SignLink causing significant tick-rate lag on servers. Lag monitoring tools show an existance of a lot of tile entities. SignLink replaces sign tile entities with an extension to handle packet sending using the function. ... Or something like it.

Needs testing, profiling and fixing

**Comment by bergerkiller** [comment]
https://github.com/bergerhealer/SignLink/commit/42da1972ae1f5a963ae781ea8af71b66c1e33d4e this commit may have fixed this problem, but I'm keeping it open in case new things show up.

**Comment by bbayu123** [comment]
Over a year ago? Nah I think this is fixed for reals

**Comment by bbayu123** [comment]
3 years now... can we just say this is fixed?

**Comment by bergerkiller** [comment]
Lol yeah I'll close it, it's been rewritten too so whatever may have caused lag doesn't really apply anymore. If people have more issues, make a new issue ticket + include a spark sampler report.
