### ISSUE TITLE
SignLink causes sign updating by other plugins to be delayed.

### ISSUE THREAD

**Issue by ykgamma** [bergerhealer/SignLink#9]
When using signlink and another plugin that changes signs (e.g. lift or cannons), the signs will be severely delayed in updating (taking about a minute). As soon as I disable signlink, those signs are updated instantly.

These signs have no signlink variables on them, so they shouldn't really be affected by signlink.

**Comment by bergerkiller** [comment]
Confirmed it on my end, let me fix it real quick

**Comment by bergerkiller** [comment]
...and then I realize a bunch of other stuff is broken. Not a quick fix at all. I'll let you know when its fixed.

**Comment by bergerkiller** [comment]
https://ci.mg-dev.eu/job/SignLink/22/

Can you see if this resolves this and other issues? My test setup changing sign text worked.

**Comment by ykgamma** [comment]
Can confirm the fix works. Non-signlink signs now update instantly, and signlink signs still work. Thanks for such a quick turnaround!
